server:
  port: 8888

spring:
  datasource:
    generate-unique-name: false
    name: bankDB
    url: jdbc:mysql://localhost:3306/bankDB?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQL5InnoDBDialect:
    hibernate:

      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin

logging:
  file:
    name: spring-boot-log