server:
  port: 8888
#  error:
#    include-binding-errors: always

spring:
  datasource:
    generate-unique-name: false
    name: bankDB
#    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:h2:~/bankDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    url: jdbc:mysql://localhost:3306/bankDB?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQL5InnoDBDialect:
    #    database: h2
    hibernate:

      ddl-auto: update
    show-sql: true
  #  h2:
#    console:
#      path: /h2-console
#      enabled: true
#      settings:
#        web-allow-others: true
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin

logging:
  file:
    name: spring-boot-log